recovery/elliptics_recovery/dc_recovery.py
recovery/elliptics_recovery/types/merge.py

Some version of eblob left several copies of one key alive. Last of them hides the rest while reading/rewriting. But iterator will return all of them. In common case it is ok because all results can be sorted by timestamp and if some key has several copies the newest (with latest timestamp) can be considered as alive and the rest as died. But it doesn't work if iterator is run with `no_meta` flag because all copies will have the same `empty` timestamp. It makes dnet_recovery with `-M/--no-meta` to recheck total_size of keys after reading first chunk.

recovery: fixed recovering keys which have several alive copies at one backend.

---

example/eblob_backend.c
tests/pytests/test_session_iterator.py

In our reality some records can be corrupted because of many issues. Iteration should skip such records if it is possible and continue iterating all valid records.  In this case it will safely skip records with corrupted extended header. While recovering all such keys will be recovered if at least one replica has a non-corrupted copy of these keys.

Iterator: skip keys which extended header can't be extracted

---

example/eblob_backend.c
example/eblob_backend.cpp
example/eblob_backend.h
example/file_backend.c
example/file_backend.cpp
example/file_backend.h
include/elliptics/backends.h
library/CMakeLists.txt
monitor/backends_stat_provider.cpp
tests/CMakeLists.txt

Provided `to_json` methods for eblob and filesystem config templates which serializes to json parsed config values. Made `fill_disabled_backend_config` to use `to_json` method of config template for filling `backend::config` with parsed config values if `to_json` is available, otherwise to fill `backend::config_template` with unparsed values from original config.

statistics: restored `backend::config` for disabled eblob and filesystem backends.

---

example/eblob_backend.c
example/eblob_backend.cpp
indexes/local_session.cpp
library/backend.cpp
library/backend.h
library/dnet_common.c
library/elliptics.h
library/net.cpp
library/node.c

Fixed crash upon generating statistics for disabled at startup backends - parse disabled backends config.
Use first local address of node instead of empty at local_session - fixed "invalid address" in logs.
Connection between servers with different number of address is not allowed at the moment. Added corresponding check to dnet_process_socket to prevent appearing for short time node with different number of addresses in dht_state_list. This short time appearance leads to crash if someone's route list request is handled at the same time.
Optimized operations with groups list: underlying structure is replaced by rbtree.

Fixes & optimization

---

bindings/python/elliptics_python.cpp
bindings/python/result_entry.cpp
bindings/python/src/id.py
example/eblob_backend.c
library/CMakeLists.txt

* Fixed indents in code.
* removed useless getters
* allow to use all `basestring` for `elliptics.Id` initialization not only `str`

Python: minor changes and cleanups

---

bindings/python/elliptics_python.cpp
bindings/python/result_entry.cpp
bindings/python/src/__init__.py
example/eblob_backend.c
include/elliptics/interface.h
include/elliptics/packet.h
library/dnet.c
recovery/elliptics_recovery/dc_recovery.py
recovery/elliptics_recovery/iterator.py
recovery/elliptics_recovery/monitor.py
recovery/elliptics_recovery/recovery.py
recovery/elliptics_recovery/types/dc.py
recovery/elliptics_recovery/types/merge.py
recovery/elliptics_recovery/utils/misc.py
tests/CMakeLists.txt
tests/pytests/conftest.py
tests/pytests/test_recovery.py
tests/pytests/test_session_monitor_and_statistics.py
tests/pytests/test_session_rwr.py

* core: added common for all backends flag `DNET_RECORD_FLAGS_UNCOMMITTED` which is set for record is uncommitted and can't be read
* iterator: made iterator collects uncommitted records
* recovery: added handling uncommitted records, added options prepare-timeout which specifies timeout for uncommitted records after which such records should be deleted
* recovery: fixed hanging on pool.close() - there is a bug in multiprocessing
* pytests: added tests that checks new flag elliptics.record_flags.uncommitted:
* serial of write_prepare, write_plain and write_commit with checking data accessibility
* new tests of merge and dc recovery with mixing uncommitted keys into recovering keys.

Added DNET_RECORD_FLAGS_UNCOMMITTED

---

library/backend.cpp
library/dnet.c
library/dnet_common.c
library/elliptics.h
library/net.c
library/node.c
library/notify.c
library/pool.c
library/route.cpp
library/trans.c
monitor/io_stat_provider.cpp
tests/CMakeLists.txt
tests/pytests/test_session_monitor_and_statistics.py
tests/test_base.cpp
tests/test_base.hpp
tests/weights_test.cpp

Issue: https://github.com/reverbrain/elliptics/issues/601
Main changes:
1) moved 'weight' from net_state to idc
2) net_state use rb-tree (mapping backend_id -> idc)
3) backend weight look up from net_state's rb-tree (idc_root)

Weights: split node weight to backends weights

---

example/eblob_backend.c
example/file_backend.c
example/module_backend/core/module_backend_t.c
include/elliptics/backends.h
library/backend.cpp
monitor/backends_stat_provider.cpp

Fixed small memory leak of `dnet_config_backend` - call cleanup.
Used const pointers for dnet_config_entry callback arguments and removed useless copying of value.

Fixes and optimizations

---

example/eblob_backend.c

`backend_id` is used to identify eblob instance at handystats statistics.

backend: added parsing backend_id by eblob_backend

---

example/eblob_backend.c

Iterator have to read header of uncommitted records because recovery checks timestamp of uncommitted records and removes too old ones.

iterator: force reading header of uncommitted records.

---

bindings/python/elliptics_session.cpp
bindings/python/src/log.py
recovery/elliptics_recovery/dc_recovery.py
recovery/elliptics_recovery/iterator.py
recovery/elliptics_recovery/monitor.py
recovery/elliptics_recovery/recovery.py
recovery/elliptics_recovery/types/dc.py
recovery/elliptics_recovery/types/merge.py
recovery/elliptics_recovery/utils/misc.py
tests/pytests/test_recovery.py
tests/pytests/test_session_iterator.py

Optimizations:
* #598 - recover keys by window - do not wait until whole batch is recovered before start to recover keys from the next batch
* #626 - allow to decrease logs by using `-L/--log-level` for both elliptics' and recovery's logs
* added `-T/--trace-id` option to dnet_recovery - allow to mark servers' logs connected with recovery
Fixes:
* fixed some recovery stats: `local_read*`, `recovered_keys*`, `remote_write*` etc.
* removed `filtered_keys` because it is always equal to `iterated_key`

Recovery: fixes and optimizations

---

bindings/cpp/session.cpp
include/elliptics/interface.h
library/dnet_common.c
library/elliptics.h
library/node.c
library/trans.c

Update them separately according to IO flags.
This should fix issue when there are obscure background disk operations while client is supposed to work in cache-only environment.

state: split backend weight into cache/disk pair

---

library/trans.c

Current implementation of transaction timeout check leads to actual wait times in range [wait_timeout, wait_timeout + 2seconds]. This PR changes check logic, so actual wait times range becomes [wait_timeout, wait_timeout + 1seconds].

timeout: accurately check timeouted transactions using microseconds

---

example/config.cpp
library/backend.cpp
library/backend.h

read_only option for backend makes backend read only at startup.

config: read_only option for backend

---

bindings/cpp/session.cpp
cache/slru_cache.cpp
example/eblob_backend.c
include/elliptics/interface.h
include/elliptics/packet.h
library/dnet.c
library/elliptics.h
tests/server_send.cpp

New IO flag which forbids overwriting data if its on-disk (or cached) timestamp is newer than that of data about to be written.
It is tested in server-send suite, by default server-send uses this flag and thus test where we write data with old timestamp and then try to move it to different groups where the same keys exist with newer timestamp. In this operation move should fail, i.e. all keys should not be moved, which implies keys will not be locally removed, and that's exactly what is tested.
Clearing timestamp cas bit (by setting iterator's overwrite flag) forces test to overwrite data, checking new content should succeed.

Timestamp cas

---

bindings/python/elliptics_python.cpp
example/ioserv.json
include/elliptics/packet.h
library/dnet_common.c
tests/pytests/test_session_parameters.py
tests/test.cpp

New IO flag which forces client to mix states according to their weights.
Sometimes it is desired to only mix states for some requests and use strict order for others, this new IO flags allows just that.
Only created for weighted mix and not randomization, since the latter can be achieved in client.

Ioflags mix states

---

bindings/cpp/session.cpp
library/dnet.c
tests/pytests/test_session_iterator.py

What about automatically setting iterator flags in cpp binding if there are ranges?

iterator: automatically set key range flag when ranges are present

---

library/net.cpp

`id_container` and `cnt` point into the memory inside `socket->buffer`, so latter should be reset after the log which prints `id_container` and `cnt`.

fixed crash caused by using freed memory

---

bindings/cpp/callback.cpp
bindings/cpp/session.cpp
library/dnet.c
library/trans.c
tests/server_send.cpp

After request has been completed, final ack will be processed both by common callback and iterator callback checkers. The latter will fail, since final ack doesn't bring any data.
This is generally worked around by using clean session clones (without checkers) and forcing aggregator to only work with clean session, i.e. apply all checkers on final aggregated results, not at intermediate replies.

Fixed server_send() aggregation error

---

tests/CMakeLists.txt
tests/run_tests.py

New `add_test_target` function is used to define a test module: its make target and any dependencies that are required to run it.
This creates the ability to build and run test modules individually (which is useful in development).
`make test` builds and runs all test modules in one go, same as before.
But, for example, `make test_srw` or `make test_api` will only build and run `dnet_cpp_srw_test` or `dnet_cpp_api_test` module.

tests: separate test targets for running test modules individually

---

tests/CMakeLists.txt
tests/run_tests.py

MERGE AFTER #670.
`add_custom_target` does not directly support setting environment for the given COMMAND, thus forcing everybody to use `A=a B=b cmd` shell syntax. But in some cases it does not work properly, as `add_custom_target` erroneously adds additional escaping and result command becomes incorrect.
Adding explicit quotes in proper places and using `env` command helps.

Fix cmake testenv handling

---

indexes/local_session.cpp
tests/cache_test.cpp

Cache sync overwrites user's timestamp, this pull request fixes that.
local_session: do not overwrite valid user's timestamp with current time
tests: added test which writes data into cache with small lifetime/sync timeout, previously cache overwrote user's timestamp with current time, this test checks that timestamp is still valid

Fixed cache timestamp overwrite

---

bindings/cpp/session.cpp
example/iterate_move.cpp
library/dnet.c
library/elliptics.h

Implemented dynamic queue size for copy/move iterator.
Instead of hardcoded (30G previously) value maximum number of bytes written and not yet acknowledged is calculated dynamically based on time every write request took to complete.
Queue size equals to 5 seconds of data written into the wire at the speed of the just finished write request. 5 seconds has been selected as it equals to default operation timeout.
This pull requests passes all tests, but also passes real-life multi-terabyte tests, which previously failed to complete with slow 'destination' disks.

Server send dynamic queue

---

example/eblob_backend.c

Removed `EBLOB_LOG_SPAM` from the switch because after
https://github.com/reverbrain/eblob/commit/f67a96f7d8e587830b6182466341cbe0815b9a82 it is equal to
`EBLOB_LOG_DEBUG`.

fixed build

---

recovery/elliptics_recovery/dc_recovery.py
recovery/elliptics_recovery/dc_server_send.py
recovery/elliptics_recovery/recovery.py
recovery/elliptics_recovery/types/dc.py
recovery/elliptics_recovery/utils/misc.py
recovery/recovery.qdoc

For detailed information see recovery/recovery.qdoc
This optimization speed up in many times dc recovery process for small/medium keys (< chunk-size == 1Mb by default).

dc_recovery: optimization: use server-send for small/medium keys

---

library/elliptics.h
library/net.c
library/pool.c
library/trans.c

The latter does not remove transaction from the timer tree and transaction may be grabbed and freed by timeout checking thread.

trans: fixed race between timeout scanning thread and completion callback

---

library/backend.cpp

Backend initialization turned out to hang-up when it failed to open or create ids file.
This commit stops backend initialization with -EINVAL error.

Fix hanging of backend initialization

---

include/elliptics/packet.h
library/dnet_common.c
library/elliptics.h
library/net.c
library/node.c
library/trans.c

2 major changes of this PR:
- move backend weight calculation to `dnet_process_recv`. This makes time used in the calculation more correct because now it does not include time spent in user's callbacks.
- use size of whole packet instead of size of read data. Read response packet consists of `[dnet_cmd][dnet_io_attr][read data]`. First two parts have fixed size, so there is no different what to use in weight calculation: size of `read data` or size of whole packet.

Update backend weight calculation

---

library/trans.c

"backend: %" was moved into `dnet_print_trans`.

logs: fix mistake in format string

---

cache/slru_cache.cpp
library/dnet.c

Cache handles lookups by sending another lookups directly to the backend,
but it is unnecessary when cache does not have the key.

Do not handle lookup by cache if it does not have the key

---

library/backend.cpp

It hangs on cache deinitialization because cache's lifecheck thread doesn't stop.
Lifecheck thread stops when either node's `need_exit` or backend's `need_exit` is set.

Fix hanging backend intialization

---

recovery/elliptics_recovery/dc_recovery.py
recovery/elliptics_recovery/dc_server_send.py
recovery/elliptics_recovery/iterator.py
recovery/elliptics_recovery/recovery.py
recovery/elliptics_recovery/types/dc.py
tests/pytests/test_recovery.py

recovery: added --user_flags option: recover key if at least one replica has user_flags from specified user_flags_set
If user_flags from all key's replicas are not in user_flags_set, then this key will be skipped during recovery. If user_flags_set is not specified (by default), then recovery will not skip any keys.

Recovery mask

---

bindings/cpp/session.cpp
example/eblob_backend.c
include/elliptics/interface.h
include/elliptics/packet.h
library/dnet.c
library/elliptics.h
library/net.c
library/node.c
library/pool.c
library/trans.c
tests/server_send.cpp

Currently neither copy/move iterator nor server-send operation allow setting write command timeout, which is vital for long-distance connections and slow links between groups. This pull request allows to set this parameter from command line options already present in all clients (python and C++ bindings).
This pull request breaks backward compatibility for server-send command, but since our internal tools are the only users of this feature, it should be ok.

Server send timeouts extension

---

bindings/python/async_result.cpp
bindings/python/async_result.h

Some operations on iterator cause waiting for new responses and without releasing GIL it sometimes leads to deadlock.

python: wrap python_async_result::iterator to free GIL in long operations
